In [3]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../nifty100.db")

pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table'
""", conn)

                name
0    sqlite_sequence
1          companies
2      profitandloss
3       balancesheet
4           cashflow
5           analysis
6          documents
7        prosandcons
8            sectors
9       stock_prices
10        market_cap
11  financial_ratios
12       peer_groups

5 RANDOM COMPANIES

In [4]:
pd.read_sql("""
SELECT id
FROM companies
ORDER BY RANDOM()
LIMIT 5
""", conn)

           id
0  HEROMOTOCO
1  TATAMOTORS
2        NHPC
3        ATGL
4       TRENT

YEAR COVERAGE

In [5]:
pd.read_sql("""
SELECT
    company_id,
    COUNT(*) AS pl_records,
    MIN(year) AS first_year,
    MAX(year) AS last_year
FROM profitandloss
WHERE company_id IN (
    'HEROMOTOCO',
    'TATAMOTORS',
    'NHPC',
    'ATGL',
    'TRENT'
)
GROUP BY company_id
ORDER BY company_id
""", conn)

   company_id  pl_records first_year last_year
0        ATGL           8   Mar 2018       TTM
1  HEROMOTOCO          12   Mar 2014       TTM
2        NHPC          13   Mar 2013       TTM
3  TATAMOTORS          13   Mar 2013       TTM
4       TRENT          13   Mar 2013       TTM

BALANCE SHEET COVERAGE

In [6]:
pd.read_sql("""
SELECT
    company_id,
    COUNT(*) AS bs_records,
    MIN(year) AS first_year,
    MAX(year) AS last_year
FROM balancesheet
WHERE company_id IN (
    'HEROMOTOCO',
    'TATAMOTORS',
    'NHPC',
    'ATGL',
    'TRENT'
)
GROUP BY company_id
ORDER BY company_id
""", conn)

   company_id  bs_records first_year last_year
0        ATGL           8   Mar 2018  Sep 2024
1  HEROMOTOCO          12   Mar 2014  Sep 2024
2        NHPC          13   Mar 2013  Sep 2024
3  TATAMOTORS          13   Mar 2013  Sep 2024
4       TRENT          13   Mar 2013  Sep 2024

CASH FLOW COVERAGE

In [7]:
pd.read_sql("""
SELECT
    company_id,
    COUNT(*) AS cf_records,
    MIN(year) AS first_year,
    MAX(year) AS last_year
FROM cashflow
WHERE company_id IN (
    'HEROMOTOCO',
    'TATAMOTORS',
    'NHPC',
    'ATGL',
    'TRENT'
)
GROUP BY company_id
ORDER BY company_id
""", conn)

   company_id  cf_records first_year last_year
0  HEROMOTOCO          11   Mar 2014  Mar 2024
1        NHPC          12   Mar 2013  Mar 2024
2  TATAMOTORS          12   Mar 2013  Mar 2024
3       TRENT          12   Mar 2013  Mar 2024

In [8]:
pd.read_sql("""
SELECT *
FROM cashflow
WHERE company_id = 'ATGL'
""", conn)

Empty DataFrame
Columns: [id, company_id, year, operating_activity, investing_activity, financing_activity, net_cash_flow]
Index: []

In [9]:
pd.read_sql("""
SELECT
    company_id,
    COUNT(*) AS years_available
FROM profitandloss
GROUP BY company_id
HAVING COUNT(*) < 5
ORDER BY years_available
""", conn)

  company_id  years_available
0     JIOFIN                3

In [10]:
pd.read_sql("""
SELECT id
FROM companies
WHERE id = 'ATGL'
""", conn)

     id
0  ATGL

In [11]:
pd.read_sql("""
SELECT COUNT(*) AS cashflow_rows
FROM cashflow
""", conn)

   cashflow_rows
0           1187

In [12]:
pd.read_sql("""
SELECT DISTINCT company_id
FROM cashflow
ORDER BY company_id
""", conn)

    company_id
0          ABB
1   ADANIENSOL
2     ADANIENT
3   ADANIGREEN
4   ADANIPORTS
..         ...
95         VBL
96        VEDL
97       WIPRO
98      ZOMATO
99   ZYDUSLIFE

[100 rows x 1 columns]